name: rag

networks:
  rag:
      driver: bridge
      ipam:
          driver: default
          config:
              - subnet: "192.168.0.0/24"
                gateway: "192.168.0.1"

services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    environment:
      - OLLAMA_HOST='0.0.0.0'
      - OLLAMA_KEEP_ALIVE=12h
    ports:
      - 11434:11434
    restart: unless-stopped
    volumes:
      - ./data/ollama:/root/.ollama
    networks:
      rag:
        ipv4_address: 192.168.0.10
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  kotaemon:
    container_name: kotaemon
    image: ghcr.io/cinnamon/kotaemon:main-full
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=80
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - ./data/kotaemon:/app/ktem_app_data
      - ./config/kotaemon/.env:/app/.env
    networks:
      rag:
        ipv4_address: 192.168.0.20
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    depends_on:
      - ollama
